const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const roles={admin:'工作室管理员',composer:'编曲师',mixer:'混音师',recording:'录音老师',teacher:'课程教师',client:'客户 / 学员'};
const roleIcons={admin:'⚙',composer:'♫',mixer:'◉',recording:'◌',teacher:'▤',client:'♥'};
const seed={
 users:[{id:'admin',name:'林嘉言',role:'admin',password:'123456'},{id:'u1',name:'苏沐',role:'composer',password:'123456'},{id:'u2',name:'叶知',role:'mixer',password:'123456'},{id:'u3',name:'周乐',role:'teacher',password:'123456'}],
 orders:[
  {id:'YT-202609-012',title:'《夏夜微光》编曲制作',client:'星野文化',type:'编曲',assignee:'苏沐',due:'2026-09-03',price:3200,status:'进行中',progress:72,description:'制作流行抒情风格完整编曲，需要包含主歌、副歌与间奏，交付工程文件及 WAV。',updates:[['2026-09-01','完成主歌与副歌编曲，已提交第一版试听。'],['2026-08-29','项目已由苏沐接单，开始进行风格与配器设计。']]},
  {id:'YT-202608-031',title:'陈默《回响》混音',client:'独立音乐人 · 陈默',type:'混音',assignee:'叶知',due:'2026-09-05',price:1800,status:'进行中',progress:48,description:'完成分轨混音，重点优化人声清晰度、空间感和整体动态。',updates:[['2026-08-31','完成主唱人声处理与基础平衡。']]},
  {id:'YT-202608-029',title:'播客片头录音制作',client:'半山电台',type:'录音',assignee:'',due:'2026-09-07',price:1200,status:'待接单',progress:0,description:'录制播客片头人声，提供录音棚预约与后期基础处理。',updates:[]},
  {id:'YT-202608-025',title:'《无声告白》人声混音',client:'陈可',type:'混音',assignee:'叶知',due:'2026-08-29',price:1500,status:'已交付',progress:100,description:'独立流行歌曲人声混音项目。',updates:[['2026-08-28','最终版本已上传，等待客户确认。']]},
  {id:'YT-202608-020',title:'品牌广告音乐制作',client:'光点设计',type:'编曲',assignee:'苏沐',due:'2026-08-26',price:4500,status:'已完成',progress:100,description:'30 秒品牌广告配乐。',updates:[['2026-08-26','客户确认完成，项目归档。']]}
 ],
 courses:[{id:'C-01',title:'基本乐理培训课程',teacher:'周乐',hours:8,price:699,students:['林小雨','陈一帆'],description:'系统学习音高、节奏、调式、音程与和弦知识。',schedule:'每周二 14:00 – 15:30',published:true},{id:'C-02',title:'和声基础培训课程',teacher:'沈悦',hours:10,price:899,students:['王若彤'],description:'学习和弦连接、和声功能与常用和声进行。',schedule:'每周二 19:30 – 21:00',published:true}],
 appointments:[]
};
let db=JSON.parse(localStorage.getItem('musicCraftDB')||'null')||seed;
let current=JSON.parse(localStorage.getItem('musicCraftUser')||'null'); let signup=false; let active='dashboard';
function save(){localStorage.setItem('musicCraftDB',JSON.stringify(db));localStorage.setItem('musicCraftUser',JSON.stringify(current))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function badge(t){return `<span class="badge ${t}">${t}</span>`}
function today(){return new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}
function canTake(o){return current&&['composer','mixer','recording'].includes(current.role)&&o.status==='待接单'&&({composer:'编曲',mixer:'混音',recording:'录音'}[current.role]===o.type)}
function myOrders(){return db.orders.filter(o=>o.assignee===current.name)}
function navItems(){let items=[['dashboard','⌂','工作台'],['market','◫','接单大厅'],['myorders','✓','我的订单']];if(current.role==='admin')items.push(['manageorders','▣','订单管理']);items.push(['courses','▤','课程中心'],['schedule','▦','排课日历']);if(current.role==='admin')items.push(['team','♙','团队成员']);return items}
function renderNav(){ $('#nav').innerHTML=navItems().map(([id,icon,name])=>`<button class="nav-item ${active===id?'active':''}" data-page="${id}"><span>${icon}</span>${name}${id==='market'?`<small>${db.orders.filter(o=>o.status==='待接单').length}</small>`:''}</button>`).join('') }
function renderShell(){if(!current){$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden');return}$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#dateText').textContent=today();$('#accountName').textContent=current.name;$('#accountRole').textContent=roles[current.role];$('#avatar').textContent=current.name.slice(0,1);renderNav();renderAll();}
function pageTitle(){return ({dashboard:'工作台',market:'接单大厅',myorders:'我的订单',manageorders:'订单管理',courses:'课程中心',schedule:'排课日历',team:'团队成员',profile:'个人中心',help:'使用帮助'})[active]}
function go(id){active=id;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$('#pageTitle').textContent=pageTitle();$('#headerAction').textContent=active==='courses'&&current.role==='teacher'?'＋ 发布课程':'＋ 新建订单';renderNav();renderAll()}
function dashboard(){let mine=myOrders();let ongoing=db.orders.filter(o=>o.status==='进行中');let nums=current.role==='admin'?{a:ongoing.length,b:db.orders.filter(o=>o.status==='待接单').length,c:db.orders.reduce((s,o)=>s+o.price,0),d:db.courses.reduce((s,c)=>s+c.students.length,0)}:{a:mine.filter(o=>o.status==='进行中').length,b:db.orders.filter(canTake).length,c:mine.reduce((s,o)=>s+o.price,0),d:db.courses.length};return `<div class="hero"><div><p>${current.role==='admin'?'本周工作概览':'欢迎回来，'+esc(current.name)}</p><h2>${current.role==='client'?'在这里预约课程、发布需求。':'选择合适任务，让专业被看见。'}</h2><span>${current.role==='admin'?'当前有 '+ongoing.length+' 个项目正在制作中，请留意交付时间。':'你有 '+nums.a+' 个进行中的订单。'}</span></div><div class="hero-wave">〰〰〰〰</div></div><div class="metrics"><article class="metric"><i>▣</i><p>${current.role==='admin'?'进行中订单':'进行中任务'}</p><strong>${nums.a}</strong><small> 个</small></article><article class="metric"><i>◷</i><p>${current.role==='admin'?'待接单订单':'可接任务'}</p><strong>${nums.b}</strong><small> 个</small></article><article class="metric"><i>￥</i><p>${current.role==='admin'?'累计订单金额':'我的订单金额'}</p><strong>¥${nums.c.toLocaleString()}</strong></article><article class="metric"><i>♧</i><p>${current.role==='admin'?'在读学员':'平台课程'}</p><strong>${nums.d}</strong><small> ${current.role==='admin'?'人':'门'}</small></article></div><div class="grid"><section class="panel"><div class="panel-head"><div><h3>${current.role==='admin'?'近期订单':'我的进行中任务'}</h3><p>查看项目进展与交付时间</p></div><button class="text-button" data-go="${current.role==='admin'?'manageorders':'myorders'}">查看全部 →</button></div>${table(current.role==='admin'?db.orders.slice(0,4):mine.slice(0,4))}</section><section class="panel"><div class="panel-head"><div><h3>交付提醒</h3><p>优先关注近期项目</p></div></div>${db.orders.filter(o=>o.status==='进行中').slice(0,3).map(o=>`<div class="deadline"><span class="day-box"><b>${o.due.slice(-2)}</b><span>交付</span></span><div><b>${esc(o.title)}</b><p>负责人：${esc(o.assignee||'待指派')}</p></div><button data-detail="${o.id}">查看</button></div>`).join('')||'<div class="empty">暂无进行中项目</div>'}</section></div>`}
function table(items){return `<div class="table-wrap"><table><thead><tr><th>项目名称</th><th>类型</th><th>负责人</th><th>交付</th><th>进度</th><th>状态</th></tr></thead><tbody>${items.map(o=>`<tr><td><b>${esc(o.title)}</b><small>${esc(o.client)}</small></td><td>${badge(o.type)}</td><td>${esc(o.assignee||'待接单')}</td><td>${o.due}</td><td><span class="mini-bar"><i style="width:${o.progress}%"></i></span>${o.progress}%</td><td>${badge(o.status)}</td><td><button class="text-button" data-detail="${o.id}">详情</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">暂无订单</td></tr>'}</tbody></table></div>`}
function market(){let eligible=db.orders.filter(o=>o.status==='待接单');return `<div class="toolbar"><div><h2>接单大厅</h2><p>浏览公开任务，按专业能力接单</p></div>${['composer','mixer','recording'].includes(current.role)?'<button class="outline" data-page="myorders">查看我的订单</button>':''}</div><div class="filters"><button class="filter active">全部任务</button><button class="filter">编曲</button><button class="filter">混音</button><button class="filter">录音</button></div><div class="order-grid">${eligible.map(o=>`<article class="order-card"><span>${badge(o.type)}</span><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div class="card-meta">客户：${esc(o.client)}<br>交付日期：${o.due}</div><div class="card-foot"><strong>¥${o.price.toLocaleString()}</strong>${canTake(o)?`<button class="secondary" data-take="${o.id}">立即接单</button>`:`<button class="secondary" data-detail="${o.id}">查看详情</button>`}</div></article>`).join('')||'<div class="empty"><b>暂无可接任务</b>管理员可创建新订单，或稍后再来看看。</div>'}</div>`}
function myOrdersView(){let list=myOrders();return `<div class="toolbar"><div><h2>我的订单</h2><p>查看订单信息、提交进度与交付成果</p></div><button class="outline" data-page="market">前往接单大厅</button></div><div class="task-grid">${list.map(o=>`<article class="task-card"><span>${badge(o.type)} ${badge(o.status)}</span><h3>${esc(o.title)}</h3><p>${esc(o.description)}</p><div class="progress"><i style="width:${o.progress}%"></i></div><small>当前进度 ${o.progress}% · 交付 ${o.due}</small><div class="card-foot"><strong>¥${o.price.toLocaleString()}</strong><button class="secondary" data-detail="${o.id}">订单操作</button></div></article>`).join('')||'<div class="empty"><b>还没有接到订单</b>前往“接单大厅”查看符合你身份的公开任务。</div>'}</div>`}
function manage(){return `<div class="toolbar"><div><h2>订单管理</h2><p>创建订单、指定负责人并跟进交付状态</p></div><button class="primary" data-new-order>＋ 新建订单</button></div><div class="filters"><button class="filter active">全部 ${db.orders.length}</button><button class="filter">待接单</button><button class="filter">进行中</button><button class="filter">已交付</button><input class="search" placeholder="搜索项目或客户"></div><section class="panel">${table(db.orders)}</section>`}
function courses(){let canPublish=current.role==='teacher'||current.role==='admin';return `<div class="toolbar"><div><h2>课程中心</h2><p>课程上架、学员预约与教学管理</p></div>${canPublish?'<button class="primary" data-new-course>＋ 发布课程</button>':''}</div><div class="course-grid">${db.courses.filter(c=>c.published).map((c,i)=>`<article class="course-card"><div class="course-cover ${i%2?'orange':''}">♫</div><span>${badge('课程')}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="card-meta">教师：${esc(c.teacher)}<br>${esc(c.schedule)} · ${c.hours} 课时<br>已预约 ${c.students.length} 人</div><div class="card-foot"><strong>¥${c.price} / ${c.hours}课时</strong>${current.role==='client'?`<button class="secondary" data-book="${c.id}">预约课程</button>`:`<button class="secondary" data-course="${c.id}">查看课程</button>`}</div></article>`).join('')}</div>`}
function schedule(){let events=db.courses.filter(c=>c.published).map((c,i)=>`<div class="event ${i%2?'orange':''}"><b>${esc(c.schedule)}</b><p>${esc(c.title)} · 授课教师：${esc(c.teacher)} · 已预约 ${c.students.length} 人</p></div>`).join('');return `<div class="toolbar"><div><h2>排课日历</h2><p>统一查看课程时间与学员安排</p></div>${(current.role==='teacher'||current.role==='admin')?'<button class="primary" data-new-course>＋ 新建排课</button>':''}</div><section class="panel"><div class="panel-head"><div><h3>本周课程安排</h3><p>课程变动将同步显示在此处</p></div></div><div class="event-list">${events||'<div class="empty">暂无课程安排</div>'}</div></section>`}
function team(){return `<div class="toolbar"><div><h2>团队成员</h2><p>按角色查看可指派的专业成员</p></div></div><div class="team-grid">${db.users.filter(u=>u.role!=='client').map(u=>`<article class="team-card"><span class="avatar">${esc(u.name[0])}</span><div><h3>${esc(u.name)}</h3><p>${roles[u.role]}</p><small>${u.role==='admin'?'可管理全部订单':'可接收对应专业订单'}</small></div></article>`).join('')}</div>`}
function profile(){let mine=myOrders();return `<div class="toolbar"><div><h2>个人中心</h2><p>管理个人身份和业务数据</p></div><button class="outline" id="logout">退出登录</button></div><div class="profile-layout"><article class="profile-card"><span class="avatar profile-avatar">${esc(current.name[0])}</span><h2>${esc(current.name)}</h2><p>${roles[current.role]}</p><dl><dt>可用功能</dt><dd>${current.role==='admin'?'订单管理、派单、课程与排课':current.role==='client'?'发布需求、预约课程、查看个人订单':'接单、订单进度、文件链接、课程信息'}</dd><dt>已接订单</dt><dd>${mine.length} 个</dd></dl></article><article class="profile-card"><h2>我的业务数据</h2>${myOrders().map(o=>`<div class="detail-block"><b>${esc(o.title)}</b><p>${badge(o.status)}　进度：${o.progress}%　交付：${o.due}</p></div>`).join('')||'<div class="empty">暂无订单记录</div>'}</article></div>`}
function help(){return `<div class="toolbar"><div><h2>使用帮助</h2><p>快速熟悉音匠工坊的核心操作</p></div></div><section class="panel"><div class="detail-block"><b>1. 如何注册成为编曲师、教师或其他成员？</b><p>退出登录后点击“立即注册”，在“注册身份”中选择编曲师、混音师、录音老师或课程教师，即可进入对应工作台。</p></div><div class="detail-block"><b>2. 如何接单和提交进度？</b><p>专业成员进入“接单大厅”领取符合身份的任务；在“我的订单”打开订单详情，可填写进度、上传文件链接并提交交付。</p></div><div class="detail-block"><b>3. 管理员如何派单？</b><p>管理员在“订单管理”创建订单后，可直接指定团队成员，或保留为“待接单”供成员自主领取。</p></div><div class="detail-block"><b>4. 如何预约和发布课程？</b><p>客户/学员可在课程中心预约。课程教师和管理员可发布课程、填写课时与课程时间。</p></div></section>`}
function renderAll(){if(!current)return;$('#dashboard').innerHTML=dashboard();$('#market').innerHTML=market();$('#myorders').innerHTML=myOrdersView();$('#manageorders').innerHTML=current.role==='admin'?manage():'';$('#courses').innerHTML=courses();$('#schedule').innerHTML=schedule();$('#team').innerHTML=current.role==='admin'?team():'';$('#profile').innerHTML=profile();$('#help').innerHTML=help();$$('.page').forEach(p=>p.classList.toggle('active',p.id===active));}
function showModal(title,eyebrow,body,foot){$('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=body;$('#modalFoot').innerHTML=foot;$('#modal').showModal()}
function orderForm(){let people=db.users.filter(u=>u.role!=='client'&&u.role!=='admin');showModal('新建商业订单','录入需求并指定负责人',`<div class="form-grid"><label>项目名称<input name="title" required placeholder="例如：《夏夜微光》编曲制作"></label><label>客户名称<input name="client" required placeholder="填写客户名称"></label><label>服务类型<select name="type"><option>编曲</option><option>混音</option><option>录音</option></select></label><label>指定负责人<select name="assignee"><option value="">暂不指定，公开接单</option>${people.map(u=>`<option>${esc(u.name)}</option>`).join('')}</select></label><label>交付日期<input name="due" type="date" required></label><label>项目报价<input name="price" type="number" required placeholder="例如：3200"></label><label class="wide">项目需求说明<textarea name="description" required placeholder="请写明制作风格、参考曲目、交付格式等"></textarea></label></div>`,`<button class="outline" value="cancel">取消</button><button class="primary" value="default" id="saveOrder">创建订单</button>`)}
function courseForm(){showModal('发布课程','创建课程并设置教学时间',`<div class="form-grid"><label>课程名称<input name="title" required placeholder="例如：基本乐理培训课程"></label><label>授课教师<input name="teacher" value="${esc(current.name)}" required></label><label>课程课时<input name="hours" type="number" value="8" required></label><label>课程价格<input name="price" type="number" value="699" required></label><label class="wide">上课安排<input name="schedule" required placeholder="例如：每周二 14:00 – 15:30"></label><label class="wide">课程简介<textarea name="description" required placeholder="填写适合人群、课程目标与主要内容"></textarea></label></div>`,`<button class="outline" value="cancel">取消</button><button class="primary" value="default" id="saveCourse">发布课程</button>`)}
function details(id){let o=db.orders.find(x=>x.id===id);if(!o)return;let editable=o.assignee===current.name;let admin=current.role==='admin';showModal(o.title,'订单详情与项目进度',`<div class="detail-block"><b>客户与项目需求</b><p>客户：${esc(o.client)}<br>${esc(o.description)}</p></div><div class="detail-block"><b>订单信息</b><p>类型：${badge(o.type)}　状态：${badge(o.status)}<br>负责人：${esc(o.assignee||'待接单')}　交付：${o.due}　报价：¥${o.price.toLocaleString()}</p></div><div class="detail-block"><b>当前进度：${o.progress}%</b><div class="progress"><i style="width:${o.progress}%"></i></div></div><div class="detail-block"><b>进度记录</b><div class="timeline">${o.updates.map(u=>`<div>${esc(u[1])}<small>${u[0]}</small></div>`).join('')||'<div>暂未提交进度<small>等待负责人开始处理</small></div>'}</div></div>`, `<button class="outline" value="cancel">关闭</button>${editable?`<button class="secondary" data-progress="${o.id}">更新进度</button>`:''}${admin&&o.status==='已交付'?`<button class="primary" data-complete="${o.id}">确认完成</button>`:''}${admin&&!o.assignee?`<button class="primary" data-assign="${o.id}">指派人员</button>`:''}`)}
function progressForm(id){let o=db.orders.find(x=>x.id===id);showModal('提交项目进度','更新制作状态并保留记录',`<div class="form-grid"><label>当前完成度<input name="progress" type="number" min="0" max="100" value="${o.progress}" required></label><label>订单状态<select name="status"><option ${o.status==='进行中'?'selected':''}>进行中</option><option ${o.status==='已交付'?'selected':''}>已交付</option></select></label><label class="wide">进度说明 / 文件链接<textarea name="note" required placeholder="例如：完成副歌编曲，试听文件：https://..."></textarea></label></div>`,`<button class="outline" value="cancel">取消</button><button class="primary" id="saveProgress" value="default" data-id="${id}">提交进度</button>`)}
function assignForm(id){let people=db.users.filter(u=>['composer','mixer','recording'].includes(u.role));showModal('指定负责人','将订单派发给团队成员',`<label>负责人<select id="chosenAssignee">${people.map(u=>`<option>${esc(u.name)} · ${roles[u.role]}</option>`).join('')}</select></label>`,`<button class="outline" value="cancel">取消</button><button class="primary" id="saveAssign" value="default" data-id="${id}">确认指派</button>`)}
function bookCourse(id){let c=db.courses.find(x=>x.id===id);showModal('预约课程','提交预约后将进入学员名单',`<div class="detail-block"><b>${esc(c.title)}</b><p>授课教师：${esc(c.teacher)}<br>${esc(c.schedule)}<br>课程费用：¥${c.price}</p></div><label>预约备注<textarea id="bookNote" placeholder="例如：已有基础、希望学习方向"></textarea></label>`,`<button class="outline" value="cancel">取消</button><button class="primary" id="confirmBook" value="default" data-id="${id}">确认预约</button>`)}
document.addEventListener('click',e=>{let p=e.target.closest('[data-page]');if(p)return go(p.dataset.page);let g=e.target.closest('[data-go]');if(g)return go(g.dataset.go);if(e.target.closest('[data-new-order]'))return orderForm();if(e.target.closest('[data-new-course]'))return courseForm();let d=e.target.closest('[data-detail]');if(d)return details(d.dataset.detail);let t=e.target.closest('[data-take]');if(t){let o=db.orders.find(x=>x.id===t.dataset.take);o.assignee=current.name;o.status='进行中';o.progress=5;o.updates.unshift([new Date().toISOString().slice(0,10),`${current.name} 已接单，开始处理项目。`]);save();toast('接单成功，已进入我的订单');renderAll();return}let pr=e.target.closest('[data-progress]');if(pr)return progressForm(pr.dataset.progress);let a=e.target.closest('[data-assign]');if(a)return assignForm(a.dataset.assign);let b=e.target.closest('[data-book]');if(b)return bookCourse(b.dataset.book);let co=e.target.closest('[data-course]');if(co){let c=db.courses.find(x=>x.id===co.dataset.course);return showModal(c.title,'课程信息',`<div class="detail-block"><b>课程内容</b><p>${esc(c.description)}</p></div><div class="detail-block"><b>教学安排</b><p>授课教师：${esc(c.teacher)}<br>${esc(c.schedule)}<br>已预约学员：${c.students.map(esc).join('、')||'暂无'}</p></div>`,`<button class="primary" value="cancel">关闭</button>`)}if(e.target.id==='headerAction')return active==='courses'&&['teacher','admin'].includes(current.role)?courseForm():orderForm();if(e.target.id==='logout'){current=null;save();renderShell();toast('已退出登录')}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))$('#modal').close()});
$('#modalForm').addEventListener('submit',e=>{let submit=e.submitter;if(!submit)return;let fd=new FormData(e.currentTarget);if(submit.id==='saveOrder'){e.preventDefault();let a=Object.fromEntries(fd);let assigned=a.assignee||'';db.orders.unshift({id:'YT-'+Date.now().toString().slice(-8),title:a.title,client:a.client,type:a.type,assignee:assigned,due:a.due,price:+a.price,status:assigned?'进行中':'待接单',progress:assigned?5:0,description:a.description,updates:assigned?[[new Date().toISOString().slice(0,10),'管理员已创建并指派订单。']]:[]});save();$('#modal').close();toast('订单已创建');renderAll()}if(submit.id==='saveCourse'){e.preventDefault();let a=Object.fromEntries(fd);db.courses.unshift({id:'C-'+Date.now().toString().slice(-5),title:a.title,teacher:a.teacher,hours:+a.hours,price:+a.price,description:a.description,schedule:a.schedule,students:[],published:true});save();$('#modal').close();toast('课程已发布');renderAll()}if(submit.id==='saveProgress'){e.preventDefault();let o=db.orders.find(x=>x.id===submit.dataset.id),a=Object.fromEntries(fd);o.progress=Math.min(100,Math.max(0,+a.progress));o.status=a.status;o.updates.unshift([new Date().toISOString().slice(0,10),a.note]);save();$('#modal').close();toast('进度已提交');renderAll()}if(submit.id==='saveAssign'){e.preventDefault();let o=db.orders.find(x=>x.id===submit.dataset.id);o.assignee=$('#chosenAssignee').value.split(' · ')[0];o.status='进行中';o.progress=5;o.updates.unshift([new Date().toISOString().slice(0,10),'管理员已完成指派。']);save();$('#modal').close();toast('已指定负责人');renderAll()}if(submit.id==='confirmBook'){e.preventDefault();let c=db.courses.find(x=>x.id===submit.dataset.id);if(!c.students.includes(current.name))c.students.push(current.name);db.appointments.push({courseId:c.id,user:current.name,note:$('#bookNote').value});save();$('#modal').close();toast('预约成功，已加入课程名单');renderAll()}});
$('#authForm').addEventListener('submit',e=>{e.preventDefault();let name=$('#authName').value.trim(),password=$('#authPassword').value;if(signup){if(db.users.some(u=>u.name===name))return toast('该姓名已注册，请直接登录');current={id:'u'+Date.now(),name,role:$('#authRole').value,password};db.users.push(current);save();toast('注册成功，欢迎加入音匠工坊')}else{let u=db.users.find(x=>x.name===name&&x.password===password);if(!u)return toast('账号或密码不正确，可使用管理员体验账号');current=u;save()}active='dashboard';renderShell()});
$('#toggleAuth').onclick=()=>{signup=!signup;$('#roleWrap').classList.toggle('hidden',!signup);$('#authTitle').textContent=signup?'创建你的账号':'欢迎回来';$('#authIntro').textContent=signup?'选择专业身份，开始接单或教学':'登录后管理你的音乐创作与教学工作';$('#authSubmit').textContent=signup?'注册并进入平台':'登录';$('#toggleAuth').textContent=signup?'已有账号？立即登录':'还没有账号？立即注册'};
$('#demoLogin').onclick=()=>{current=db.users.find(u=>u.role==='admin');save();active='dashboard';renderShell()};
renderShell();
// 管理员确认客户验收后，将订单归档为已完成。
document.addEventListener('click',e=>{const done=e.target.closest('[data-complete]');if(!done)return;const order=db.orders.find(o=>o.id===done.dataset.complete);if(!order)return;order.status='已完成';order.progress=100;order.updates.unshift([new Date().toISOString().slice(0,10),'管理员已确认客户验收，订单已完成。']);save();$('#modal').close();toast('订单已归档为已完成');renderAll()});
