const orders=[
 {id:'YT-202609-012',name:'《夏夜微光》编曲制作',client:'星野文化',type:'编曲',person:'苏沐',date:'09月03日',state:'进行中',cls:'working',price:'¥ 3,200',progress:72},
 {id:'YT-202608-031',name:'陈默《回响》混音',client:'独立音乐人 · 陈默',type:'混音',person:'叶知',date:'09月05日',state:'进行中',cls:'working',price:'¥ 1,800',progress:48},
 {id:'YT-202608-029',name:'播客片头录音制作',client:'半山电台',type:'录音',person:'许墨',date:'09月07日',state:'待接单',cls:'waiting',price:'¥ 1,200',progress:0},
 {id:'YT-202608-025',name:'《无声告白》人声混音',client:'陈可',type:'混音',person:'叶知',date:'08月29日',state:'已交付',cls:'delivered',price:'¥ 1,500',progress:100},
 {id:'YT-202608-020',name:'品牌广告音乐制作',client:'光点设计',type:'编曲',person:'苏沐',date:'08月26日',state:'已完成',cls:'done',price:'¥ 4,500',progress:100}
];
const typeClass=t=>t==='混音'?'mix':t==='录音'?'record':'';
function orderRow(o,full=false){return `<tr>${full?`<td>${o.id}</td>`:''}<td><strong>${o.name}</strong><small>${o.client}</small></td><td><span class="type ${typeClass(o.type)}">${o.type}</span></td><td>${o.person}</td>${full?`<td>${o.price}</td>`:''}<td>${o.date}</td><td><span class="status ${o.cls}">${o.state}</span></td>${full?'<td class="ellipsis">···</td>':''}</tr>`}
function render(){document.querySelector('#recentOrders').innerHTML=orders.slice(0,4).map(o=>orderRow(o)).join('');document.querySelector('#allOrders').innerHTML=orders.map(o=>orderRow(o,true)).join('');document.querySelector('#progressList').innerHTML=orders.filter(o=>o.progress>0&&o.progress<100).map(o=>`<div class="progress-row"><div class="project-line"><strong>${o.name}</strong><span>${o.progress}%</span></div><div class="bar"><i style="width:${o.progress}%"></i></div></div>`).join('')}
render();
const tasks=[['《夏夜微光》编曲制作','编曲商业订单','苏沐','完成主歌与副歌编曲，提交第一版试听文件','72'],['陈默《回响》混音','混音商业订单','叶知','完成人声处理与整体声场平衡','48'],['播客片头录音制作','录音业务订单','许墨','确认录音时间并准备录音工程','0']];
document.querySelector('#taskCards').innerHTML=tasks.map((t,i)=>`<article class="task-card"><span class="type ${i===1?'mix':i===2?'record':''}">${t[1]}</span><h3>${t[0]}</h3><p>${t[3]}</p><div class="bar"><i style="width:${t[4]}%"></i></div><div class="task-footer"><small>当前进度 ${t[4]}%</small><button>更新进度</button></div></article>`).join('');
const people=[['苏','苏沐','编曲师','编曲 / 配器 / 制作','purple'],['叶','叶知','混音师','混音 / 母带 / 声音设计','pink'],['许','许墨','录音老师','录音 / 人声指导','gold'],['周','周乐','基本乐理教师','乐理教学 / 课程设计','green'],['沈','沈悦','和声教师','和声教学 / 作品分析','purple']];
document.querySelector('#memberGrid').innerHTML=people.map(p=>`<article class="member"><div class="avatar big ${p[4]}">${p[0]}</div><div><h3>${p[1]}</h3><p>${p[2]}</p><small>${p[3]}</small></div></article>`).join('');
const days=document.querySelector('#calendarDays');for(let d=1;d<=35;d++){let n=d<=30?d:'';let e=n==1?'<div class="event">14:00 乐理课</div>':n==2?'<div class="event orange-event">19:30 和声课</div>':n==8?'<div class="event">14:00 乐理课</div>':'';days.innerHTML+=`<div class="day ${n==1?'today':''}">${n}${e}</div>`}
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#'+btn.dataset.page).classList.add('active');document.querySelector('#pageTitle').textContent=btn.textContent.replace(/\d+/g,'').trim()}));
document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>document.querySelector(`.nav[data-page="${btn.dataset.go}"]`).click());
const dialog=document.querySelector('#orderDialog');document.querySelector('#newOrder').onclick=()=>dialog.showModal();document.querySelector('#newOrder2').onclick=()=>dialog.showModal();
document.querySelector('#saveOrder').onclick=e=>{const name=document.querySelector('#projectName').value,client=document.querySelector('#clientName').value,service=document.querySelector('#service').value,person=document.querySelector('#assignee').value.split(' · ')[0],date=document.querySelector('#dueDate').value,price=document.querySelector('#price').value;if(!name||!client||!date||!price){e.preventDefault();return}orders.unshift({id:'YT-202609-'+String(orders.length+13).padStart(3,'0'),name,client,type:service.slice(0,2),person,date:date.slice(5).replace('-','月')+'日',state:'待接单',cls:'waiting',price:'¥ '+Number(price).toLocaleString(),progress:0});render();};
